CREATE TABLE board_game
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    min_players INTEGER,
    max_players INTEGER,
    rating      NUMERIC(2,1),
    image_url   VARCHAR(255),
    CONSTRAINT pk_board_game PRIMARY KEY (id)
);